//Create abstract class account having member id. name, balance
//Id is generated by application write  read only property for ID.
//It has abstract method public abstract void withdraw(double amt);
//It has deposit method which will increase the balance.
//Write getter setter for name 
//Balance can be set only by child class.
//It has static double int_rate = 0.07
//Create two child class Saving, Current
//Initialise data by calling parent class constructor
//In saving account maintain minimum balance 1000 for this declare
//Const double minbal=1000
//In current account negative balance allowed.
//Let both child class override withdraw method.
//Create array of account class and store 2 object of saving account and current account.
//Do the transaction. When you load it should print name of bank.


using System;

namespace BankApplication
{
    abstract class Account
    {
        private static int count = 0;
        private int id;
        private string name;
        private double balance;
        public static double int_rate = 0.07;
        public static string bankName = "MyBank";

        public Account(string name, double balance)
        {
            this.id = ++count;
            this.Name = name;
            this.balance = balance;
        }

        public int Id
        {
            get { return id; }
        }

        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        public double Balance
        {
            get { return balance; }
            protected set { balance = value; }
        }

        public void Deposit(double amt)
        {
            Balance += amt;
        }

        public abstract void Withdraw(double amt);

        public override string ToString()
        {
            return $"ID: {Id}, Name: {Name}, Balance: Rs {Balance}";
        }
    }

    class Saving : Account
    {
        private const double minbal = 1000;

        public Saving(string name, double balance) : base(name, balance) { }

        public override void Withdraw(double amt)
        {
            if (Balance - amt >= minbal)
            {
                Balance -= amt;
                Console.WriteLine($"{Name} withdrew Rs{amt}. New Balance: Rs{Balance}");
            }
            else
            {
                Console.WriteLine($"Withdrawal denied for {Name}. Minimum balance of {minbal:C} must be maintained.");
            }
        }
    }

    class Current : Account
    {
        public Current(string name, double balance) : base(name, balance) { }

        public override void Withdraw(double amt)
        {
            Balance -= amt;
            Console.WriteLine($"{Name} withdrew Rs{amt}. New Balance: Rs{Balance}");
        }
    }

    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Welcome to " + Account.bankName + "\n");

            Account[] accounts = new Account[2];
            accounts[0] = new Saving("Alice", 5000);
            accounts[1] = new Current("Bob", 3000);

            // Transactions
            accounts[0].Deposit(2000);
            accounts[1].Deposit(1000);

            accounts[0].Withdraw(4500); // Should be denied if below min balance
            accounts[1].Withdraw(5000); // Can go negative

            Console.WriteLine("\nAccount Details:");
            foreach (Account acc in accounts)
            {
                Console.WriteLine(acc);
            }

            Console.ReadLine();
        }
    }
}
