//Q12 Create application CG HR APP
//create abstract class Employee with member Id, Firstname, Lastname, salary, netsal.
//Id should be generated by your application.
//Write getter setter for , Firstname, Lastname, salary For salary write protected setter.
//It has method givesalary which will deducte 10% tds and set Netsalary.
//It has abstract method givebonud().
//Create 2 child class Permanent employee and Contract Employee.
//In Permanent employee , give bonus of 10% in Contract Employee, give bonus of 5%.
//As soon as employee get Bonus send sms and email using delegate.
//Create array of Employee class and store 3 child class.
//As soon as application get loaded print name of company.
//Ensure that use enter salary >1000.
//First name and lastname must be minimum 3 character and maximum 15 character.
//Handel all necessary exception.
//Call methods and display state of object using Tostring method in c#
using System;

namespace CGHRApp
{
    public delegate void Notify(string message);
    
    public abstract class Employee
    {
        private static int idCounter = 1; 
        public int Id { get; private set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        protected decimal salary;
        public decimal NetSalary { get; private set; }

        public Employee()
        {
            Id = idCounter++;
        }

        public decimal GetSalary()
        {
            return salary;
        }

        protected void SetSalary(decimal value)
        {
            if (value <= 1000)
                throw new ArgumentException("Salary must be greater than 1000.");
            salary = value;
            CalculateNetSalary();
        }

        private void CalculateNetSalary()
        {
            NetSalary = salary - (salary * 0.10m); 
        }

        public abstract decimal GiveBonus();

        public override string ToString()
        {
            return $"Id: {Id}, Name: {FirstName} {LastName}, Salary: {salary}, Net Salary: {NetSalary}";
        }
    }

    public class PermanentEmployee : Employee
    {
        public event Notify OnBonusReceived;

        public PermanentEmployee(string firstName, string lastName, decimal salary)
        {
            FirstName = firstName;
            LastName = lastName;
            SetSalary(salary);
        }

        public override decimal GiveBonus()
        {
            decimal bonus = salary * 0.10m; 
            OnBonusReceived?.Invoke($"Bonus of {bonus} received by {FirstName} {LastName}");
            return bonus;
        }
    }

    public class ContractEmployee : Employee
    {
        public event Notify OnBonusReceived;

        public ContractEmployee(string firstName, string lastName, decimal salary)
        {
            FirstName = firstName;
            LastName = lastName;
            SetSalary(salary);
        }

        public override decimal GiveBonus()
        {
            decimal bonus = salary * 0.05m; 
            OnBonusReceived?.Invoke($"Bonus of {bonus} received by {FirstName} {LastName}");
            return bonus;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Welcome to CG HR APP");

            Employee[] employees = new Employee[3];

            try
            {
                employees[0] = new PermanentEmployee("John", "Doe", 1500);
                employees[1] = new ContractEmployee("Jane", "Smith", 2000);
                employees[2] = new PermanentEmployee("Alice", "Johnson", 2500);

                ((PermanentEmployee)employees[0]).OnBonusReceived += SendNotification;
                ((ContractEmployee)employees[1]).OnBonusReceived += SendNotification;
                ((PermanentEmployee)employees[2]).OnBonusReceived += SendNotification;

                foreach (var employee in employees)
                {
                    Console.WriteLine(employee);
                    Console.WriteLine($"Bonus: {employee.GiveBonus()}");
                }
            }
            catch (ArgumentException ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An unexpected error occurred: {ex.Message}");
            }
        }

        static void SendNotification(string message)
        {
            Console.WriteLine($"Notification: {message}");
        }
    }
}