//Q10 Create a Account class having instance member  id, name , balance. 
//Id should be generated by your application. Using parameterised constructor initialised member
//It has instance method  public void deposit(double amt) who’s job is to increase the instance balance.
//It has public abstract void withdraw(double amt); Create child Saving account and override 
//public override void withdraw(double amt) { }
//method which will reduce balance. Create reference of Account class which will point to child class object.
//Using parent reference call deposit and withdraw method. Using to string method display ID name and balance.


using System;

namespace BankingSystem
{
    public abstract class Account
    {
        protected int Id;
        protected string Name;
        protected double Balance;

        public Account(string name)
        {
            Id = new Random().Next(1000, 9999); // Generate random Id
            Name = name;
            Balance = 0;
        }

        public void Deposit(double amt)
        {
            Balance += amt;
            Console.WriteLine($"Deposited: {amt}, New Balance: {Balance}");
        }

        public abstract void Withdraw(double amt);

        public override string ToString()
        {
            return $"Id: {Id}, Name: {Name}, Balance: {Balance}";
        }
    }

    public class SavingAccount : Account
    {
        public SavingAccount(string name) : base(name) { }

        public override void Withdraw(double amt)
        {
            if (amt > Balance)
            {
                Console.WriteLine("Insufficient balance.");
            }
            else
            {
                Balance -= amt;
                Console.WriteLine($"Withdrawn: {amt}, New Balance: {Balance}");
            }
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Account myAccount = new SavingAccount("John Doe");
            myAccount.Deposit(1000);
            myAccount.Withdraw(500);
            myAccount.Withdraw(600); // Should show insufficient balance
            Console.WriteLine(myAccount);
        }
    }
}