//Q9.Create class Employee with private member Id, name, salary.
//Write parameterized constructor in this constructor call
//setter method for name and salary but id should be generated by your application.
//Write getter setter for name and salary but for Id  you will write only getter property.
//Create 3 object and display Id, name and salary using To string method.


using System;

namespace EmployeeManagement
{
    public class Employee
    {
        private static int idCounter = 1;
        private int Id;
        private string Name;
        private decimal Salary;
        public Employee(string name, decimal salary)
        {
            Id = idCounter++;
            Name = name;
            Salary = salary;
        }

        public string GetName() => Name;
        public decimal GetSalary() => Salary;
        public int GetId() => Id;

        public override string ToString()
        {
            return $"Id: {Id}, Name: {Name}, Salary: {Salary}";
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Employee emp1 = new Employee("Alice", 50000);
            Employee emp2 = new Employee("Bob", 60000);
            Employee emp3 = new Employee("Charlie", 70000);

            Console.WriteLine(emp1);
            Console.WriteLine(emp2);
            Console.WriteLine(emp3);
        }
    }
}