//Create Account class having instance member 
//1. id- id should be generated by application, it is readonly property
//2. name – write getter setter 
//3. balance- Write getter setter 
//It has deposit method who’s job is to increase the balance.
//Declare static float Interestrate = 0.07.
//It has withdraw method who’s job is to reduce balance.
//Declare conts float minbal=1000. When user withdraw money your application should ensure that minimum balance is maintain. 
//Give appropriate validation like user can not deposit or withdraw 0 or negative. user can not open account with 0 amount
//When you run your application at the beginning it should print name of bank and copy right detail.
//It has static method which will calculate and return  interest amount for each account holder and increase the balance.
//Write display method who’s job is to display Id name and balance and interest received.
//If you are comfortable the exception try to use it and handle it also.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Text;
using System.Threading.Tasks;
using System;

namespace BankApplication
{
    class Account
    {
        // Static Fields
        private static int lastId = 1000; // Auto-increment ID
        public static float InterestRate = 0.07f; // 7% interest
        public const float MinBalance = 1000f;

        // Instance Fields
        private readonly int id;
        private string name;
        private float balance;
        private float lastInterest;

        // Constructor
        public Account(string name, float initialBalance)
        {
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentException("Name cannot be empty.");

            if (initialBalance < MinBalance)
                throw new ArgumentException($"Initial balance must be at least {MinBalance}.");

            this.id = ++lastId;
            this.Name = name;
            this.Balance = initialBalance;
        }

        // Readonly Property
        public int Id => id;

        // Name Property
        public string Name
        {
            get => name;
            set
            {
                if (string.IsNullOrWhiteSpace(value))
                    throw new ArgumentException("Name cannot be empty.");
                name = value;
            }
        }

        // Balance Property
        public float Balance
        {
            get => balance;
            private set => balance = value;
        }

        public float LastInterest => lastInterest;

        // Deposit Method
        public void Deposit(float amount)
        {
            if (amount <= 0)
                throw new ArgumentException("Amount must be greater than 0.");
            Balance += amount;
        }

        // Withdraw Method
        public void Withdraw(float amount)
        {
            if (amount <= 0)
                throw new ArgumentException("Amount must be greater than 0.");

            if (Balance - amount < MinBalance)
                throw new InvalidOperationException($"Insufficient balance. Minimum balance of {MinBalance} must be maintained.");

            Balance -= amount;
        }

        // Calculate Interest
        public static float CalculateInterest(Account acc)
        {
            float interest = acc.Balance * InterestRate;
            acc.balance += interest;
            acc.lastInterest = interest;
            return interest;
        }

        // Display Account Info
        public void Display()
        {
            Console.WriteLine("--------------------------------------------------");
            Console.WriteLine($"Account ID     : {Id}");
            Console.WriteLine($"Account Holder : {Name}");
            Console.WriteLine($"Balance        : Rs{Balance:F2}");
            Console.WriteLine($"Interest Earned: Rs{LastInterest:F2}");
            Console.WriteLine("--------------------------------------------------\n");
        }

        // Static Method - Bank Info
        public static void ShowBankInfo()
        {
            Console.WriteLine("==================================================");
            Console.WriteLine("             WELCOME TO ABC BANK");
            Console.WriteLine("           © 2025 ABC Bank Ltd. India");
            Console.WriteLine("==================================================\n");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Account.ShowBankInfo();

                // Create first account
                Account acc1 = new Account("Prabhat", 5000);
                acc1.Deposit(2000);
                acc1.Withdraw(1500);
                Account.CalculateInterest(acc1);
                acc1.Display();

                // Create second account
                Account acc2 = new Account("Richa", 3000);
                acc2.Deposit(1000);
                acc2.Withdraw(500);
                Account.CalculateInterest(acc2);
                acc2.Display();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[ERROR]: {ex.Message}");
            }

            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }
    }
}
