//Q3.Create class Employee with member Id, Firstname, Lastname, Middlename, salary, netsal.
//Id should be generated by your application.
//Your  application should able to create object of employee if user enter  only Firstname and Lastname salary.
//It also should able to create object when user enter all 4 Firstname, Lastname, Middlename, salary.
//As soon as application get loaded print name of company.
//Create method CalculateNetsal which will set netsall after deducting TDS of 10%.
//Declare TDS as Static variable.
//Declare public const int maxcapacity = 3.
//Your application should create only 3 object if you try to create 4 object it will not allow you to create.
//Ensure that use enter salary >1000.
//First name and lastname must be minimum 3 character and maximum 15 character.
//Handel all necessary exception

using System;

public class Employee
{
    private static int _idCounter = 1;
    private static int _currentCount = 0;
    public const int MaxCapacity = 3;
    public static double TDS = 0.10;

    public int Id { get; private set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string MiddleName { get; set; }
    public double Salary { get; set; }
    public double NetSalary { get; private set; }

    public Employee(string firstName, string lastName, double salary, string middleName = null)
    {
        if (_currentCount >= MaxCapacity)
            throw new InvalidOperationException("Cannot create more than 3 employees.");

        if (firstName.Length < 3 || firstName.Length > 15 || lastName.Length < 3 || lastName.Length > 15)
            throw new ArgumentException("First and Last name must be between 3 and 15 characters.");

        if (salary <= 1000)
            throw new ArgumentException("Salary must be greater than 1000.");

        Id = _idCounter++;
        FirstName = firstName;
        LastName = lastName;
        Salary = salary;
        MiddleName = middleName;
        CalculateNetSalary();
        _currentCount++;
    }

    private void CalculateNetSalary()
    {
        NetSalary = Salary - (Salary * TDS);
    }
}

class Program
{
    static void Main()
    {
        try
        {
            Employee[] employees = new Employee[Employee.MaxCapacity];
            employees[0] = new Employee("John", "Doe", 2000);
            employees[1] = new Employee("Jane", "Smith", 2500, "A.");
            employees[2] = new Employee("Alice", "Johnson", 3000);

            foreach (var employee in employees)
            {
                Console.WriteLine($"Id: {employee.Id}, Name: {employee.FirstName} {employee.LastName}, Salary: {employee.Salary}, Net Salary: {employee.NetSalary}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
    }
}