//Q6.Create abstract class account having member id. name, balance
//Id is generated by application write read only property for ID.
//It has abstract method public abstract void withdraw(double amt);
//It has deposit method which will increase the balance.
//Write getter setter for name 
//Balance can be set only by child class.
//It has static double int_rate = 0.07
//Create two child class Saving, Current
//Initialise data by calling parent class constructor
//In saving account maintain minimum balance 1000 for this declare
//Const double minbal=1000
//In current account negative balance allowed.
//Let both child class override withdraw method.
//Create array of account class and store 2 object of saving account and current account.
//Do the transaction. When you load it should print name of bank.
//Also display all account detail name wise ascending order.


using System;

public abstract class Account
{
    private static int _idCounter = 1;
    public int Id { get; private set; }
    public string Name { get; set; }
    public double Balance { get; set; }

    public static double IntRate = 0.07;

    public Account(string name)
    {
        Id = _idCounter++;
        Name = name;
    }

    public abstract void Withdraw(double amt);

    public void Deposit(double amt)
    {
        Balance += amt;
    }
}

public class Saving : Account
{
    private const double MinBal = 1000;

    public Saving(string name) : base(name) { }

    public override void Withdraw(double amt)
    {
        if (Balance - amt < MinBal)
            throw new InvalidOperationException("Insufficient balance.");
        Balance -= amt;
    }
}

public class Current : Account
{
    public Current(string name) : base(name) { }

    public override void Withdraw(double amt)
    {
        Balance -= amt; // Negative balance allowed
    }
}

class Program
{
    static void Main()
    {
        Account[] accounts = new Account[4];
        accounts[0] = new Saving("Alice");
        accounts[1] = new Current("Bob");

        accounts[0].Deposit(5000);
        accounts[1].Deposit(3000);

        accounts[0].Withdraw(2000);
        accounts[1].Withdraw(1000);

        Console.WriteLine("Account details:");
        foreach (var account in accounts)
        {
            Console.WriteLine($"Id: {account.Id}, Name: {account.Name}, Balance: {account.Balance}");
        }
    }
}