//using ConsoleApp1;
//Create a Account class having instance member
// id, firstname, LastName, MiddleName, bal. 
//Id should be generated by your application. 
//Interest rate for  account is 7%. 
//Do not allow your application to create object if firstname is <3 and opening balance is<=0.
//It has instance method 
//public void deposit(double amt) who’s job is to increase the instance balance.
//It has instance method 
//public void withdraw(double amt) who’s job is to reduce the instance balance
// It has static method payint(public static double payint(Account obj)) who’s job is to calculate interest of each saving account holder and increase balanace and retun interest amount. 
//Create instance method display who’s job is to display Name and bal. 
//Create 3 object of account class. As soon as application load it should display name of bank.
//Create 3 constructor let one constructor write logic to validate firstname can not be <3 character
//Your application should create only 3 object if you try to create 4th object show error.
using System;

public class Account
{
    static int counter = 0;
    static int maxAccounts = 3;
    static int nextId = 1;
    private static readonly double interestRate = 0.07;
    private static readonly string bankName = "MyBank";

    int id;
    string firstName;
    string lastName;
    string middleName;
    double balance;

    static Account()
    {
        Console.WriteLine("Welcome to " + bankName);
    }

    public Account(string firstName, string lastName, string middleName, double bal)
    {
        if (counter >= maxAccounts)
            throw new Exception("Maximum account limit reached. Cannot create more than 3 accounts.");

        if (firstName.Length < 3)
            throw new ArgumentException("Firstname must be at least 3 characters long.");

        if (bal <= 0)
            throw new ArgumentException("Opening balance must be greater than 0.");

        this.id = ++nextId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.balance = bal;

        counter++;
    }

    public Account(string firstName, string lastName, double bal)
        : this(firstName, lastName, "", bal)
    {
    }

    public Account(string firstName, string lastName)
        : this(firstName, lastName, "", 100) 
    {
    }

    public void Deposit(double amt)
    {
        if (amt > 0)
            balance += amt;
    }

    public void Withdraw(double amt)
    {
        if (amt > 0 && amt <= balance)
            balance -= amt;
    }

    public static double PayInterest(Account obj)
    {
        double interest = obj.balance * interestRate;
        obj.balance += interest;
        return interest;
    }

    public void Display()
    {
        Console.WriteLine($"Name: {firstName} {lastName} | Balance: Rs {balance}");
    }
}

public class Program
{
    public static void Main()
    {
        try
        {
            Account a1 = new Account("Ravi", "Raj", 5000);
            Account a2 = new Account("Neha", "Sharma", 7000);
            Account a3 = new Account("Amit", "Singh");

            a1.Deposit(1000);
            a2.Withdraw(500);
            double interest = Account.PayInterest(a3);

            a1.Display();
            a2.Display();
            a3.Display();
            Console.WriteLine($"Interest added to {a3}: Rs {interest}");

            Account a4 = new Account("John", "Doe", 4000);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Error: " + ex.Message);
        }
    }
}
